version: '3.6'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch01
    environment: 
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    ports: 
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
        
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana01
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch01:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch01:9200
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch
    networks:
      - elastic

networks: 
  elastic:
    driver: bridge